/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountPortfolioRouteImport } from './routes/account.portfolio'
import { Route as AccountCashRouteImport } from './routes/account.cash'

const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPortfolioRoute = AccountPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCashRoute = AccountCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/account/cash': typeof AccountCashRoute
  '/account/portfolio': typeof AccountPortfolioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/account/cash': typeof AccountCashRoute
  '/account/portfolio': typeof AccountPortfolioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/account/cash': typeof AccountCashRoute
  '/account/portfolio': typeof AccountPortfolioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/account/cash' | '/account/portfolio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/account/cash' | '/account/portfolio'
  id: '__root__' | '/' | '/account' | '/account/cash' | '/account/portfolio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/portfolio': {
      id: '/account/portfolio'
      path: '/portfolio'
      fullPath: '/account/portfolio'
      preLoaderRoute: typeof AccountPortfolioRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/cash': {
      id: '/account/cash'
      path: '/cash'
      fullPath: '/account/cash'
      preLoaderRoute: typeof AccountCashRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountCashRoute: typeof AccountCashRoute
  AccountPortfolioRoute: typeof AccountPortfolioRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountCashRoute: AccountCashRoute,
  AccountPortfolioRoute: AccountPortfolioRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
